// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Salon.Api.Data;

#nullable disable

namespace Salon.Api.Migrations
{
    [DbContext(typeof(SalonDbContext))]
    [Migration("20260906221340_InitServices")]
    partial class InitServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Salon.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ออกแบบทรงผมตามสไตล์ที่คุณชอบ ด้วยช่างผมมืออาชีพ",
                            DurationMinutes = 45,
                            ImageUrl = "/images/haircut.jpg",
                            IsActive = true,
                            MaxPrice = 300m,
                            MinPrice = 300m,
                            NameEn = "Haircut",
                            NameTh = "ตัดผม"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "เปลี่ยนลุคใหม่ด้วยสีผมออร์แกนิค ถนอมเส้นผมและหนังศีรษะ",
                            DurationMinutes = 120,
                            ImageUrl = "/images/hair-coloring.jpg",
                            IsActive = true,
                            MaxPrice = 2500m,
                            MinPrice = 1500m,
                            NameEn = "Hair Coloring",
                            NameTh = "ทำสีผม"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ฟื้นฟูผมเสียให้กลับมานุ่มสลวย เงางาม",
                            DurationMinutes = 60,
                            ImageUrl = "/images/hair-treatment.jpg",
                            IsActive = true,
                            MaxPrice = 800m,
                            MinPrice = 800m,
                            NameEn = "Hair Treatment",
                            NameTh = "ทรีทเม้นท์บำรุงผม"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ออกแบบลายเล็บสวยๆ ด้วยเจลคุณภาพ สีสดใสติดทน",
                            DurationMinutes = 90,
                            ImageUrl = "/images/nail-art.jpg",
                            IsActive = true,
                            MaxPrice = 500m,
                            MinPrice = 500m,
                            NameEn = "Nail Art",
                            NameTh = "เพ้นท์เล็บเจล"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
